// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserLibrary.Models;

#nullable disable

namespace UserLibrary.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260508050829_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserLibrary.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(6)");

                    b.HasKey("RoomId");

                    b.HasIndex("CreateByUserId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("UserLibrary.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserLibrary.Models.Room", b =>
                {
                    b.HasOne("UserLibrary.Models.User", "UserNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("UserLibrary.Models.User", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
