// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemperatureLibrary.Models;

#nullable disable

namespace TemperatureLibrary.Migrations
{
    [DbContext(typeof(TemperatureDbContext))]
    [Migration("20260511063025_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemperatureLibrary.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("VARCHAR(6)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TemperatureLibrary.Models.Temperature", b =>
                {
                    b.Property<string>("ReadingId")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("RecordedAt")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(6)");

                    b.Property<decimal>("TemperatureValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReadingId");

                    b.HasIndex("RoomId");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("TemperatureLibrary.Models.Temperature", b =>
                {
                    b.HasOne("TemperatureLibrary.Models.Room", "RoomNavigation")
                        .WithMany("Temperatures")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomNavigation");
                });

            modelBuilder.Entity("TemperatureLibrary.Models.Room", b =>
                {
                    b.Navigation("Temperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
