// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomsLibrary.Models;

#nullable disable

namespace RoomsLibrary.Migrations
{
    [DbContext(typeof(RoomDbContext))]
    [Migration("20260512033230_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomsLibrary.Models.Alert", b =>
                {
                    b.Property<string>("AlertId")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(6)");

                    b.HasKey("AlertId");

                    b.HasIndex("RoomId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("RoomsLibrary.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(6)");

                    b.Property<int>("MaxTemp")
                        .HasColumnType("int");

                    b.Property<int>("MinTemp")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("RoomId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("RoomsLibrary.Models.Temperature", b =>
                {
                    b.Property<string>("ReadingId")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(6)");

                    b.HasKey("ReadingId");

                    b.HasIndex("RoomId");

                    b.ToTable("Tempratures");
                });

            modelBuilder.Entity("RoomsLibrary.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR(6)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoomsLibrary.Models.Alert", b =>
                {
                    b.HasOne("RoomsLibrary.Models.Room", "RoomNavigation")
                        .WithMany("Alerts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomNavigation");
                });

            modelBuilder.Entity("RoomsLibrary.Models.Room", b =>
                {
                    b.HasOne("RoomsLibrary.Models.User", "userNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userNavigation");
                });

            modelBuilder.Entity("RoomsLibrary.Models.Temperature", b =>
                {
                    b.HasOne("RoomsLibrary.Models.Room", "RoomNavigation")
                        .WithMany("Temperatures")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomNavigation");
                });

            modelBuilder.Entity("RoomsLibrary.Models.Room", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Temperatures");
                });

            modelBuilder.Entity("RoomsLibrary.Models.User", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
