// <auto-generated />
using AlertsLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlertsLibrary.Migrations
{
    [DbContext(typeof(AlertDbContext))]
    [Migration("20260505040442_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertsLibrary.Models.Alert", b =>
                {
                    b.Property<string>("AlertId")
                        .HasColumnType("CHAR(6)");

                    b.Property<string>("AlertTime")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("CHAR(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AlertId");

                    b.ToTable("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
